### ISSUE TITLE
Composer requires erusev/parsedown

### ISSUE THREAD

**Issue by mindplay-dk** [mnapoli/FrontYAML#9]
`composer.json` says the library requires `erusev/parsedown`, is that true?

It should be "recommends" maybe, rather than requires? Since we have the bridge adapters.

**Comment by vinkla** [comment]
Correct me if I'm wrong but doesn't it use ParsedownParser as the default parser? Therefore we need to require it by default.

**Comment by mindplay-dk** [comment]
Hmm, yeah, it just seems a bit odd to require it to be installed, when using it is optional.

**Comment by vinkla** [comment]
Out of the box it is used.

**Comment by mindplay-dk** [comment]
> Out of the box it is used.

Sometimes, optionally, and necessarily no Markdown engine is even used at all - it's odd to be forced to install something that is entirely optional.

You can use this library without it - it's not a hard dependency. IMO, that's when you make libraries recommended or optional - it's not technically "required", so it shouldn't be "required" in `composer.json`.

I would say "recommended" is the right setting - Composer will then prompt and ask you whether you want to install the recommended dependency, which seems appropriate.

**Comment by mnapoli** [comment]
I understand the issue you are raising. Originally there was only one very good parser in PHP (e.g. just like Symfony\Yaml for yaml) and it seemed OK to require it so that this package would be easy to use.

It would make sense in a v2 (because BC) to not require it anymore. That way users can use any of the 2 adapters provided (parsedown or league/markdown) or anything else.

The question is: is it something we should do now? I'm not against it, but given it's a new version for just this small change is it worth it?

**Comment by vinkla** [comment]
+1 on adding the `suggest` array to the composer.json with all markdown parsers. IMO we should throw an error if the developers haven't included a parser.

**Comment by kelunik** [comment]
@vinkla Only if `parseMarkdown` is set to `true`, otherwise there's no need for a parser.

**Comment by mnapoli** [comment]
https://github.com/mnapoli/FrontYAML/pull/26 switches entirely to CommonMark, as it's much better than Parsedown.

Parsedown won't be required anymore.

FYI I still require CommonMark and symfony/yaml by default because I want this package to work out of the box.
